apiVersion: apps/v1
kind: Deployment
metadata:
  name: pc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pc-frontend
  template:
    metadata:
      labels:
        app: pc-frontend
    spec:
      containers:
        - name: pc-frontend
          image: gcr.io/podcast-search-430411/pc-frontend:latest
          ports:
            - containerPort: 3001
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: 'http://pc-backend.default:3000' # Updated to use the backend's Kubernetes service name
---
apiVersion: v1
kind: Service
metadata:
  name: pc-frontend
spec:
  selector:
    app: pc-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
  loadBalancerIP: 34.96.251.84
