apiVersion: batch/v1
kind: CronJob
metadata:
  name: podcast-automation
spec:
  schedule: '0 0 * * *' # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: podcast-automation
              image: gcr.io/podcast-search-430411/podcast-automation:latest
              env:
                - name: OPENAI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: podcast-secrets
                      key: OPENAI_API_KEY
                - name: ELASTICSEARCH_HOST
                  value: 'http://elasticsearch:9200' # Updated to use the Elasticsearch service name
                - name: ELASTICSEARCH_USERNAME
                  value: 'elastic'
                - name: ELASTICSEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: podcast-secrets
                      key: ELASTICSEARCH_PASSWORD
                - name: INDEX_NAME
                  value: podcast
                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      name: podcast-secrets
                      key: MONGO_URI
                - name: MONGO_DB
                  value: 'podcastDB'
                - name: MONGO_COLLECTION
                  value: 'episodes'
              command:
                - /bin/sh
                - -c
                - |
                  # Run the processing script
                  python main.py test
              resources: # Add resource requests and limits here
                requests:
                  memory: '256Mi'
                  cpu: '250m'
                limits:
                  memory: '512Mi'
                  cpu: '500m'
          restartPolicy: Never
      backoffLimit: 0
