name: Deploy to GKE

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: pc-cluster # Add your cluster name here.
  GKE_ZONE: asia-east2 # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test # Add your deployment name here.
  IMAGE: static-site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build and push backend Docker image
      - name: Build and push backend Docker image
        run: |
          docker build -t gcr.io/podcast-search-430411/pc-backend:latest ./backend
          docker push gcr.io/podcast-search-430411/pc-backend:latest

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          docker build -t gcr.io/podcast-search-430411/pc-frontend:latest ./frontend
          docker push gcr.io/podcast-search-430411/pc-frontend:latest
      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Deploy using kubectl apply
      - name: Deploy Backend
        run: |
          kubectl apply -f deployment/backend-deployment.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f deployment/frontend-deployment.yaml
