name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY_FILE }}

      # Step 3: Set up gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: podcast-search-430411
          install_components: kubectl

      # Step 4: Get GKE Credentials
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials pc-cluster --zone asia-east2 --project podcast-search-430411

      # Step 5: Configure Docker authentication
      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      # Step 6: Build and push backend Docker image
      - name: Build and push backend Docker image
        run: |
          docker build -t  us-docker.pkg.dev/gcr.io/podcast-search-430411/pc-backend:latest ./backend
          docker push us-docker.pkg.dev/gcr.io/podcast-search-430411/pc-backend:latest

      # Step 7: Build and push frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          docker build -t us-docker.pkg.dev/gcr.io/podcast-search-430411/pc-frontend:latest ./frontend
          docker push us-docker.pkg.dev/gcr.io/podcast-search-430411/pc-frontend:latest

      # Step 8: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment/backend-deployment.yaml
          kubectl apply -f deployment/frontend-deployment.yaml
