name: Deploy to GKE

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY_FILE }}

      # Configure gcloud
      - name: Configure gcloud
        run: |
          gcloud config set project podcast-search-430411
          gcloud config set compute/zone asia-east2
          gcloud container clusters get-credentials pc-cluster

      # Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      # Configure Docker for GCR/Artifact Registry
      - name: Configure Docker for GCR/Artifact Registry
        run: |
          gcloud auth configure-docker

      # Build and push backend Docker image
      - name: Build and push backend Docker image
        run: |
          docker build -t gcr.io/podcast-search-430411/pc-backend:latest ./backend
          docker push gcr.io/podcast-search-430411/pc-backend:latest

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          docker build -t gcr.io/podcast-search-430411/pc-frontend:latest ./frontend
          docker push gcr.io/podcast-search-430411/pc-frontend:latest

      # Deploy using kubectl apply
      - name: Deploy Backend
        run: |
          kubectl apply -f deployment/backend-deployment.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f deployment/frontend-deployment.yaml
